id: P8EEE3E45
initial_creation_type: input
source_metadata:
  title: Pilgrimage Series
  language: en
  description: 'Lotsawa House presents the following texts related to pilgrimage (gnas
    skor) and major sacred places (gnas):'
  volume:
    89c6cb8bb36448a5bb77d812067ee9b3:
      title: The Three Types of Pilgrim
      parent: General
    12c073fa31e840968c06da3a849eaaa9:
      title: A Guide to Uḍḍiyāna (Ujjain), Benglor
      parent: Sacred Places
    cecb856c23714e6f8dd7912d405c9a4f:
      title: 'Melodious Tambura of Delight: A Guide to Māratika Cave, Supreme Site
        of Immortality'
      parent: Sacred Places
    f7996c23ffc74c55b3c4b3fac30ae25e:
      title: A Brief Petitionary Offering to the Mātṛkā Pukkasī, Local Protectress
        of the Jarung Kashor Stūpa
      parent: Sacred Places
    d4b64f7510c346b398797cfcae6787c6:
      title: Prayer to the Three Great Stūpas of Kathmandu
      parent: Sacred Places
    397a7e4c8efc4c6ca2098e0d85573460:
      title: A Prayer to the Stūpa of Jarung Khashor in Boudha
      parent: Sacred Places
    fc987a85a9d44aa1afe356322837664e:
      title: A Prayer to the Svayambhū Stūpa in Nepal
      parent: Sacred Places
    bb8cc66a246b4abd92ba332ae2a7ea35:
      title: A Prayer to the Three Stūpas of Nepal
      parent: Sacred Places
    bd20407b231f40e99757faa36cb2b5d1:
      title: A Short Guide to Yangleshö in Nepal
      parent: Sacred Places
    e2afe20d8b614f008cc62a88423eecb1:
      title: 'A Song of Perfect Joy: In Praise of the Sacred Sites of Rājgṛha, Vulture
        Peak and Nālandā'
      parent: Sacred Places
    4dc083d00cd342c0a7cef81274a70ebd:
      title: 'Gathering Auspiciousness: A Prayer of Aspiration Made in the Presence
        of the Sacred Mahābodhi Temple and its Imagery, Magadha, Land of the Āryas'
      parent: Sacred Places
    c40cd91662e3466ca58a3bbfe6aeedf4:
      title: Guide to Sengchen Namdrak
      parent: Sacred Places
    598dc3c182ba4c2b9f77b15e3343c987:
      title: In Praise of Devāvatāra, Site of Buddha's Descent from Heaven
      parent: Sacred Places
    c17d931446a147248f78011171dd67ae:
      title: In Praise of Kuśinagara
      parent: Sacred Places
    fd65fdf520f74e4e92ec9303c2c5d5b7:
      title: In Praise of Vārāṇasī, the Supreme Place
      parent: Sacred Places
    d30b2eddb0d0402185eae688e34f2f42:
      title: In Praise of Yangleshö in Nepal
      parent: Sacred Places
    b94f46317804469494bc9825a8565a97:
      title: In Praise of the Great Indian City of Kolkata
      parent: Sacred Places
    2b75ecc6a9ff4059a6b9eb45e02ead8d:
      title: Offering Clouds to Delight the Victorious Ones, Combining A Praise of
        Redreng with a Prayer of Aspiration
      parent: Sacred Places
    6b7f36ec5d7246cb907c364c46514c0f:
      title: Praise and Prayer to Kharchu, Great Sacred Place of Lhodrak
      parent: Sacred Places
    6639253ac3aa4cb9b31abdba88435c89:
      title: Prayer of Aspiration to the Stūpa Commemorating the Bodily Sacrifice
        to the Tigress
      parent: Sacred Places
    ee00af127b684373b12a9346dd9488c0:
      title: 'The Conquerors'' Delight: In Praise of Śrāvastī'
      parent: Sacred Places
    d1af5453e9b14772b320301c2db0f099:
      title: 'The White Lotus Garland of Immortality: In Praise of the Supreme Vajra
        Place, Tso Pema (Lotus Lake)'
      parent: Sacred Places
    8ffef2d826434409bf4024f4aa3410ad:
      title: 'The White Lotus: In Praise of Lumbinī'
      parent: Sacred Places
    23377955ddb54fe892c247270e4059ed:
      title: The Guidebook to the Hidden Land of Pemokö
      parent: Sacred Places
    8b413e44cf6f491997fa4286f328c75b:
      title: A Prayer to Jowo Rinpoche Combined with Aspirations and a Means to Receive
        the Four Empowerments
      parent: Sacred Places
    471dd2b428074d9ea8db3bdede30feec:
      title: 'The Kalaviṅka’s Call: A Guide to Glorious Samye Chimphu'
      parent: Sacred Places
    9766313d50234c82bf633787845bf185:
      title: Upon Arriving at Yangleshö
      parent: Sacred Places
    6c75cfe5982044eba6ec1082362308e6:
      title: An Aspiration to Travel to the Hidden Land of Pemokö
      parent: Sacred Places
    b227de38a8d649fcbe2076db48a1c1a3:
      title: Jangphen Namkha Dzong
      parent: Sacred Places
    059ab91673a64669945911dafb74c50d:
      title: 'Liberation Upon Hearing: The History of the Great Jarung Kashor Stūpa'
      parent: Sacred Places
    afb78e92adf14803b5ed5eb610fac1c0:
      title: 'Melodious Sound: In Praise of Vulture Peak Mountain'
      parent: Sacred Places
    84813bb694ca4ed3a7893952efca71ef:
      title: In Praise of the Hidden Valley of Kyimolung
      parent: Sacred Places
    5127330f641b44a6b27a0fd963606fcf:
      title: 'Auspicious Dance of Longevity: A Song for Touring the Sacred Sites of
        Nepal'
      parent: Songs
created_at: '2022-03-01T05:06:14.965607'
last_modified_at: '2022-03-01T05:06:14.965614'
